<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>JNS.SshTerminal</AssemblyName>
    <RootNamespace>JnsSshTerminal</RootNamespace>
    <Version>0.1.4</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VirtualTerminal.WPF" Version="1.10.0" />
    <PackageReference Include="VirtualTerminal.SecureShell" Version="1.10.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

</Project>
