name: Build JNS Secure SFTP app

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "jns_secure_sftp/**"
      - ".github/workflows/build_sftp_app.yml"

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: jns-secure-sftp
  VERSION: "0.3.2"

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and push image
        uses: home-assistant/builder/actions/build-image@4de35182ce1e329181bffcbcc84d33db5e2c7e10
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/${{ github.repository_owner }}/${{ matrix.arch }}-${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ env.VERSION }}
            latest
          push: "true"
          version: ${{ env.VERSION }}
          context: ./jns_secure_sftp
